# Generated by Django 3.0.5 on 2020-08-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronadata',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
