# Generated by Django 3.0.5 on 2020-08-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0004_auto_20200830_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronadata',
            name='total',
            field=models.IntegerField(),
        ),
    ]
