# Generated by Django 3.0.5 on 2020-08-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0005_auto_20200830_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronadata',
            name='today',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
