# Generated by Django 3.0.5 on 2020-08-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0006_coronadata_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronadata',
            name='today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coronadata',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
