# Generated by Django 3.0.5 on 2020-08-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0007_auto_20200830_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronadata',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
