# Generated by Django 3.0.5 on 2020-08-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0008_coronadata_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coronadata',
            name='test',
        ),
    ]
