# Generated by Django 3.0.5 on 2020-08-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0010_coronadata_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coronadata',
            old_name='test',
            new_name='t',
        ),
    ]
