# Generated by Django 3.0.5 on 2020-08-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0011_auto_20200830_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coronadata',
            options={'managed': False, 'verbose_name_plural': '코로나 데이터'},
        ),
    ]
