# Generated by Django 3.0.5 on 2020-08-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0012_auto_20200830_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coronadata',
            options={},
        ),
    ]
